fullLinkText1 = "artificial intelligence"
partialLinkText = "artificial"
newArticleTitle = ""
articleName1 = "Final Fantasy XII"
articleName2 = "Google"
articleName3 = "Scotland"
articleName3_finnish = "Skotlanti"

finnishLanguage = "Suomi"

referencesElementId = "content_block_19"
fullLinkTextCapitalized = "Artificial intelligence"
readingListName = "Fancy stuff"
article1_referenceSubHeading = "References"
article1_firstSubHeading = "Gameplay"
newTabDefaultText = "Main Page"

article1_subheading1 = "Gameplay"
article1_subheading2 =  "Plot"
article1_subheading3 = "Development"
article1_firstReference = "Gantayat, Anoop"
referencesJSClassName = "app_table_collapsed_caption"